### ISSUE TITLE
Some or all mail within unified inbox not shown on startup - together with tentative diagnosis

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [Betterbird/thunderbird-patches#455]
I am trying out Betterbird. Usually I use Thunderbird. I set Betterbird to use my existing Thunderbird profile. All seemed to work until after a few reboots. At that point, running Betterbird showed only one of the messages in my unified inbox, even though the tree pane showed all my accounts listed under the unified inbox and even though previously Betterbird had shown all of the (multiple) messages there. Waiting for thirty seconds did not help. I restarted Betterbird. That time is showed no messages in the inbox at all. I ran Thunderbird itself: all the messages in the inbox - some ten of them - were displayed. Looking within the various discrete inboxes did reveal the emails that it should.

**Things that did not help**

- Clearing the startup cache
- The 'troubleshooting mode' (which by design lacks a unified inbox).

***Aha!***

In Betterbird, and specifically the unified inbox settings, 'search online' was disabled. _I think I know how that happened - and it could bite other users._ Upon the first run of Betterbird, I had set up no accounts. For, I had expected my Thunderbird profile to be used; it was not; I thought that later I could get Betterbird to use that profile; and I did manage that, via the `p` switch. I think that all of this somehow set the unified inbox to operate off-line. Once I had enabled 'search online', my emails appeared. The Junk folder too had become set to offline - but not Sent Mail or Deleted.

**My system**

|   |  |
| ------------- | ------------- |
| OS | Windows 10 Pro x86_64 |
| Kernel | WIN32_NT 10.0.19045.5965 (22H2) |
| GPU | AMD Radeon (TM) RX 460 Series (3.98 GiB) (Discrete) |
| Memory | 6.27 GiB / 15.95 GiB (39%) |
| Swap | 316.84 MiB / 3.42 GiB (9%) |
| Disk (C:\) | 92.03 GiB / 231.17 GiB (40%) - NTFS. Contains Betterbird. |
| Disk (D:\) | 15.92 GiB / 470.25 GiB (3%) - NTFS. Contains my emails. |
| Disk (R:\) | 17.55 MiB / 539.38 MiB (3%) - exFAT. Contains my Thunderbird (and Betterbird?) disk cache. |
| Anti-virus | Eset Nod32 |
| Betterbird | 128.11.1esr-bb29 (64-bit) |
| Thunderbird  | 128.11.0esr (64-bit)  |

_Accounts_: three IMAP; one 'feed'. Many local folders. Inbox contains some ten messages. All of those emails - including the one that at one point was all that were displayed - are from my 'Mailfence' account.

No CalDav or NextCloud or similar.

I have this userChrome.css:

```
/* For alternating rows */
@namespace html url("http://www.w3.org/1999/xhtml");
#threadTree tr:nth-child(2n) {
  background-image: linear-gradient(rgba(255,255,255,.15), rgba(255,255,255,.15)) !important;
}
```

As said: Thunderbird does not have the problem.

**Comment by LinuxOnTheDesktop** [comment]
**Update**: _the problem recurred_, _after_ setting the unified inbox to online mode! 'Repairing' the Mailfence inbox did not help. Weirdly, clicking the 'local folders' inbox and then returning to the unified inbox (the top-level inbox) did help: all my emails appeared. But I have to do that every time I restart Betterbird. For, until I do so, my unified inbox is blank.

**Comment by Betterbird** [comment]
> As said: Thunderbird does not have the problem.

It's not clear what the problem really is. Some comments:

1. This looks like a support request, so we will close the ticket.
2. Yes, one difference between TB and BB is that the virtual folder definitions don't have "search online" set by default.
3. One difference between TB and BB is that BB caches all virtual folders.
4. Rather then repairing inboxes, you should use the "Update" button to refresh the unified/virtual/search folder.
5. Sometimes it helps to remove `Mail\smart mailboxes`.
6. This is the first report of "unified inbox is blank". We would have a sh*t storm if this were a problem affecting all users.

**Comment by LinuxOnTheDesktop** [comment]
Do you infer 1 from 6?

**Comment by LinuxOnTheDesktop** [comment]
&nbsp;&nbsp;&nbsp;The following make me infer tentatively that what we have here is a bug.

- TB lacks the problem.
- BB has caching TB lacks.
- I see this:

![Image](https://github.com/user-attachments/assets/1f3b6c51-7527-405d-bf5a-872fbc26da21)

**Comment by Betterbird** [comment]
Please follow the advice given in points 4. and 5.

Also, refer to our support page:
https://www.betterbird.eu/support/#virtual-folders

And please switch from your demanding tone to a more cooperative one.

**Comment by LinuxOnTheDesktop** [comment]
Thank you for suggestions 4 and 5. Upon your suggestion, I tried them. I am afraid that they did not help.

If I have been somewhat forceful then I take it that that is because I got the impression that you yourself could have been more cooperative.

I shall work through the further suggestions contained in the document that you linked.

**Comment by LinuxOnTheDesktop** [comment]
There _has been_ another report similar to mine: please see [here](https://github.com/Betterbird/thunderbird-patches/issues/237#issuecomment-1858803513).

**Comment by Betterbird** [comment]
Virtual folders were reworked after issue #237.

You need to submit the virtual folder debugging as detailed here: https://www.betterbird.eu/support/#virtual-folders

In summary, all folders contributing to a virtual folder need to be repaired so we can be sure that the respective caches can be stored correctly. Then the virtual folder needs to be "Updated". The virtual folder caching implementation has a long history and we worked with a user who had a very complicated setup on very slow hardware until all problems were solved, see issue #368 (and related ones).

**Comment by LinuxOnTheDesktop** [comment]
Thanks.

I had already done the following, to no avail.

1) I sought the string 'No table returned' in the error console. I found no such message. I have uploaded the log [here](https://gist.github.com/LinuxOnTheDesktop/e835a75b0c30aa2518db82e0245b6cef).
2) I deleted all the directories that I could find that were called 'smart mailbox' and similar.
3) I 'updated' the virtual inbox folder.
4) I deleted 'virtualfolders.dat' from my Thunderbird profile.
5) I removed and recreated my main email account.

I have (only) skimmed #368. Surely it is hard to be sure - barring a deductive proof or similar - that _all_ problems in some area have been solved.

**Comment by Betterbird** [comment]
> 1. I have uploaded the log [here](https://gist.github.com/LinuxOnTheDesktop/e835a75b0c30aa2518db82e0245b6cef).

The is zero virtual folder debugging in the log. However, there are plenty of potentially harmful add-ons making noise:
QNoteExtension and QuickFolders. Try without them. You need to follow the support page to turn it on.

Deleting virtualfolders.dat wasn't suggested and is pretty fatal since it obliterates all virtual folder definitions.

We're deep into a support case here and free troubleshooting of individual problems is rather limited, see the statement on the support page.

**Comment by LinuxOnTheDesktop** [comment]
I forgot to enable `mailnews.virtual_folders.verbose`. Sorry.

I appreciate your help but I have kept saying that I _think_ there might be a bug here.

Just now I disabled all AddOns, repaired a folder that seemed to be identified by a 'no table returned' debug message, used the 'update' button, and restarted Betterbird. The 'no table returned' message was gone - but the problem persisted. I cleared the startup cache. No dice.

It may be relief to you to know that at this point I give up. I will return to Thunderbird.

**Comment by Betterbird** [comment]
You will understand that even of there were a bug, we couldn't fix it without a reproducible case.

BTW, the verbose debugging tells you exactly what's going on, for example on first access:
`Cross-folder virtual view not using cache: First access, update or invalid cache.`

And later on repeated access:
`Search folder mailbox://nobody@smart%20mailboxes/Inbox: View populated with retrieved cache hits:`
followed by a list of contributing folders.

You said that your unified folder is displayed empty, so surely the cause for this will be in the debug output.
